src/app/app.component.html, src/app/client/administrator/administrator.component.html, src/app/time/time.component.css, src/app/time/time.component.html, src/app/time/time.component.ts
`time.component.ts:`
- Ensured that the time updates every second and the date is displayed along with the time.
- Updated to include a method for formatting the date as "Day, Month date, year".
`time.component.html:`
- Added the formatted date display below the time.
`time.component.css:`
- Added styling for the time and date.
`administrator.component.html:`
- Integrated the updated TimeComponent into the administrator page to show both time and date.
=> Enhance TimeComponent to Display Current Time and Date on Administrator Page

src/app/time/time.component.html
- make animation of clock slide from top
- make animation of date slide from below
=> Working clock animation

src/app/client/services/services.component.html
- fix issuance cards gap and padding
=> Services page

src/app/admin/borrow-info/borrow-info.component.html, src/app/admin/borrow/borrow.component.html, src/app/admin/borrow/borrow.component.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/client/material-info/material-info.component.html, src/app/client/material-info/material-info.component.spec.ts, src/app/client/material-info/material-info.component.ts
- borrow-info component (page when title in borrow table is clicked)
- material-info component (page when title in search a book (clientside) is clicked)
=> Modify page layouts

controller_lis/fetch_material_details.php, src/app/admin/borrow-info/borrow-info.component.html, src/app/admin/borrow-info/borrow-info.component.ts, src/app/admin/borrow/borrow.component.html, src/app/admin/borrow/borrow.component.ts, src/app/app-routing.module.ts, src/services/materials.service.ts
**Front-end:**
- update title column text in borrow component to look clickable by changing text color, and adding hover effect
**Functionality:**
- When material title is clicked, pass accession number as parameter to borrow-info component
- Added path in app routing module to handle parameters
- Updated material service to handle getting material details
- Display details from database to respective input fields in borrow-info component (if database field empty display "null" keyword) 
**Backend**
- Add fetch_materials.php to handle fetching material details from database using query parameters
=> Implement clickable material titles for borrow component

src/app/admin/borrow-info/borrow-info.component.html, src/app/admin/borrow-info/borrow-info.component.ts, src/app/admin/borrow/borrow.component.html
- change text color of title when hovered
- add routerlink on back button in borrow-info
- change the "null" word to "unknown/empty" if the field is empty
=> borrowing book

src/app/admin/borrow-info/borrow-info.component.css, src/app/admin/borrow-info/borrow-info.component.html
- add floating labels on each input field 
- make input fields "readonly" except for borrower id number
=> Floating labels on borrow-info

controller_lis/check_timein.php, controller_lis/check_user.php, controller_lis/get_records.php, controller_lis/get_time_logs.php, controller_lis/time_in.php, controller_lis/time_out.php, src/app/admin/records/records.component.html, src/app/admin/records/records.component.ts, src/app/app.component.html, src/app/app.module.ts, src/app/client/time-in/time-in.component.html, src/app/client/time-in/time-in.component.ts, src/app/client/time-out/time-out.component.html, src/app/client/time-out/time-out.component.ts, src/services/records.service.spec.ts, src/services/records.service.ts, src/services/time-log.service.spec.ts, src/services/time-log.service.ts
1. **PHP Scripts:**
- Created `check_user.php` to verify user registration based on role (Student, Faculty, Visitor) and return the corresponding `user_id`.
- Created `time_in.php` to log time-in entry for the user with accurate local timezone handling.
- Created `check_timein.php` to check if a user has already time-in but not yet time-out by verifying their identifier (student number or employee number) and `user_id`.
- Created `time_out.php` to log the time-out entry for the user with accurate local timezone handling.
- Created `get_time_logs.php` to fetch logs for students, faculty, and visitors based on the provided log type. This script consolidates the previous individual scripts for each role.
- Created `get_records.php` to fetch default student records including student number, …
=> Implement Time-In and Time-Out Functionality; Dynamic Fetching of Logs and Student Records

src/app/admin/borrow-info/borrow-info.component.css, src/app/admin/borrow-info/borrow-info.component.html, src/app/admin/borrow/borrow.component.html, src/app/admin/borrow/borrow.component.ts, src/app/admin/records/records.component.html, src/app/admin/records/records.component.ts, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/client/landing/landing.component.html, src/app/client/timein-already/timein-already.component.html, src/app/client/timein-already/timein-already.component.spec.ts, src/app/client/timein-already/timein-already.component.ts
- fix the height of image in landing page and all components
- revert the placeholder for borrower id number in borrow-info component
=> fix height of Landing image

src/app/admin/records/records.component.html, src/app/client/register/register.component.html, src/app/client/time-in/time-in.component.ts
- change the middle name field of visitors in registration to "identifier"
- fix layout of table in records page to stay on top
- fix the placeholder of contact number (email removed)
=> Visitor registration and modify table in records page

controller_lis/check_timein.php, controller_lis/check_user.php, controller_lis/register.php, src/app/client/register/register.component.html, src/app/client/register/register.component.ts, src/app/client/time-in/time-in.component.ts, src/services/register.service.ts, src/services/time-log.service.ts
1. Updated `register.component.ts` to handle form submissions for visitors.
2. Updated `register.php` script to handle the registration of visitors.
3. Included logic to insert visitor details into the `visitors` table, ensuring the correct handling of the `identifier` field.
4. Adjusted SQL queries to ensure data is stored correctly in the updated column order.
1. Updated `time-in.component.ts` to handle time-in form submission for the visitor.
2. Updated `check_timein.php` to check if a user has already timed in but not yet timed out by verifying their identifier (student number, employee number, or visitor identifier) and user_id.
1. `time-in.component.ts`: Added logic to check if the user has already timed in without timing out and redirects to `timein-already.component.html` if true. …
=> Implement Visitor Registration and Time-In/Time-Out Functionality with Double Time-In Prevention

controller_lis/fetch_materials.php, src/app/admin/borrow/borrow.component.html, src/app/admin/borrow/borrow.component.ts, src/services/materials.service.ts
**Several enhancements made to the fetch_materials.php file and the related Angular components to support category-based filtering and improved search functionality. Below is a summary of the changes made:**
`(fetch_materials.php):`
- Added Category Filtering: Modified the SQL query to include category-based filtering if a category is specified. This involves adjusting both the material retrieval and total count queries to account for the selected category.
Updated Parameter Binding: Updated the parameter binding to handle the optional category parameter and ensure correct SQL execution.
___
`(borrow.component.html):`
- Updated Category Links: Modified the category links in the HTML to use a new format that is consistent with the backend category filtering logic.
___ …
=> implement category filter in borrow component

.gitignore, src/app/app-routing.module.ts, src/app/client/material-info/material-info.component.html, src/app/client/material-info/material-info.component.ts, src/app/client/search-book/search-book.component.html, src/app/client/search-book/search-book.component.ts
`search-book.component.html`
- Update book title to look clickable
`search-book.component.ts`
- Implement working category filter
- Implement category filter with search bar
- Allow navigation to material-info.html to show complete details
- Identify specific material by accession number pass it as query parameter
`app-routing.module.ts`
- Add path to material-info containing query parameters
`material-info.component.ts`
- Accept query parameter and assign values to the input fields
`material-info.component.html`
- Display material details into its corresponding input fields
=> implement ability to view complete material info from search-book.component

controller_lis/admin_login.php, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/client/administrator/administrator.component.html, src/app/client/administrator/administrator.component.ts, src/services/admin-login.service.spec.ts, src/services/admin-login.service.ts, src/services/admin.service.spec.ts, src/services/admin.service.ts
- Created `admin_login.php` to verify user credentials from the librarian and admin tables.
- Created `admin-login.service.ts` to handle HTTP requests for logging in.
- Updated `administrator.component.ts` to handle login form submission and direct administrator to the appropriate component based on their role.
- Created `admin.service.ts` and used `BehaviorSubject` to manage and share the user role state across components.
- Updated `app.component.ts` and `app.component.html` to dynamically load the `<app-sidebar-admin>` or `<app-super-admin>` components based on the administrator role.
=> implement administrator login

src/app/admin/borrow-info/borrow-info.component.css, src/app/admin/borrow-info/borrow-info.component.html, src/app/client/register/register.component.html, src/app/client/time-in/time-in.component.ts
- add note in visitor registration for identifier
- fix layout of borrow info
- fix placeholder of faculty in time in page
=> Visitor and faculty Registration, Borrow-info layout

src/app/app.module.ts, src/app/super-admin/add-user/add-user.component.html, src/app/super-admin/add-user/add-user.component.spec.ts, src/app/super-admin/add-user/add-user.component.ts, src/app/super-admin/super-admin.component.html
- create add-user component for super admin
=> Add-user component for superadmin

src/app/admin/sidebar-admin/sidebar-admin.component.html, src/app/app-routing.module.ts, src/app/app.component.html, src/app/super-admin/super-sidebar/super-sidebar.component.html
- add superadmin pages
- route the pages in buttons on sidebar
- fix structure of superadmin in app component
=> Superadmin pages

controller_lis/update_material.php, src/app/admin/add-success/add-success.component.html, src/app/admin/add-success/add-success.component.ts, src/app/admin/materials-add/materials-add.component.html, src/app/admin/materials-add/materials-add.component.ts, src/app/admin/materials-edit/materials-edit.component.html, src/app/admin/materials-edit/materials-edit.component.ts, src/app/admin/materials-success/materials-success.component.html, src/app/admin/materials-success/materials-success.component.ts, src/app/app.module.ts, src/app/client/material-info/material-info.component.html, src/app/client/material-info/material-info.component.ts, src/app/super-admin/books/books.component.html, src/services/materials.service.ts
`app.module.ts`
- Imported ReactiveFormsModule
___
`materials-edit.component.html`
- Removed input field for category and replaced it with dropdown selector
- Replaced component navigation to modal display for edit confirmation
- Fetched data from database and passed it inside the input fields using query parameter
___
`materials-edit.component.ts`
- Added mapping for category, category is identified through the "categoryid"
- Use category mapping logic to assign the value of the category to the dropdown for category
- Get the new values form the input fields to be passed to the `material.service.ts`
- The values will be passed to the specific book/material which will be determined by the "categoryid"
___
`material.service.ts`
- Add updateMaterial method to access the backend api: …
=> implement edit material feature in material component under admin side

controller_lis/delete_material.php, controller_lis/fetch_materials.php, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts, src/services/materials.service.ts
`book.componenet.html`
- Add modal for delete confirmation
- Bind delete button with material.id for each row to track each individual delete button
- Add snack bar to inform user of successful deletion of material
___
`book.componenet.ts`
- Pass the material.id received from button click to the `material.service.ts`
- Implement showing and closing of modal
- Implement showing and closing of snackbar 
___
`material.service.ts`
- Add deleteMaterial method to connect to `delete_material.php`
- Receive material.id from `book.componenet.ts` and pass it to `delete_material.php`
___
`delete_material.php`
- Backend logic for deleting a material from the materials table in the database,  based on the material.id received from the front-end
=> implement delete feature under super admin

controller_lis/get_records.php, controller_lis/update_student_details.php, src/app/app-routing.module.ts, src/app/super-admin/edit-student/edit-student.component.html, src/app/super-admin/edit-student/edit-student.component.ts, src/app/super-admin/edit-success/edit-success.component.html, src/app/super-admin/edit-success/edit-success.component.ts, src/app/super-admin/student/student.component.html, src/services/records.service.ts
`get_records.php`
- add switch case for when user_id is passed and record type is student, response should be a single student's details
- backend logic for fetching a single student's details
___
`update_student_details.php`
- backend logic for updating the selected student by user_id
___
`app-routing.module.ts`
- modified path for edit-student to take a query parameter
___
`edit-student.component.ts`
- front-end logic for getting the selected students data from the backend and storing them to be displayed in the html
- added a confirmation modal to ask is user wants to save the changes they made
___
`edit-student.component.html`
- display selected student details on the input fields and select the option in the dropdown based on existing student details
___
`edit-success.component`
- …
=> implement edit feature for students under super admin

controller_lis/get_records.php, controller_lis/update_visitor.php, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/super-admin/add-visitor-success/add-visitor-success.component.html, src/app/super-admin/add-visitor-success/add-visitor-success.component.spec.ts, src/app/super-admin/add-visitor-success/add-visitor-success.component.ts, src/app/super-admin/add-visitor/add-visitor.component.html, src/app/super-admin/add-visitor/add-visitor.component.ts, src/app/super-admin/edit-visitor/edit-visitor.component.html, src/app/super-admin/edit-visitor/edit-visitor.component.ts, src/app/super-admin/user-record/user-record.component.html, src/app/super-admin/user-record/user-record.component.ts, src/app/super-admin/visitor/visitor.component.html, src/services/records.service.ts
- Set `currentLogType` to 'student_log' as the default in the `UserRecordComponent`.
- Modified the `clearLogType` method to reset the log type to 'student_log'.
- Updated the button styles in `user-record.component.html` to reflect the default selection.
- Implemented the `add-visitor.component.html` template for the visitor addition form.
- Created a confirmation modal that appears before finalizing the addition of a visitor.
- Created an `add-visitor-success` component to display a success message after successfully adding a visitor.
**To-Do**
- Fix the edit function for visitor records to ensure data can be populated and updated correctly. The implementation needs to be completed to allow proper editing of visitor information.
=> Ensure Student Log is Default in User Records Component in super-admin

controller_lis/db_connection.php, controller_lis/delete_student.php, controller_lis/get_records.php, src/app/admin/materials-type/materials-type.component.html, src/app/admin/materials-type/materials-type.component.ts, src/app/super-admin/add-faculty/add-faculty.component.html, src/app/super-admin/add-student/add-student.component.html, src/app/super-admin/add-student/add-student.component.ts, src/app/super-admin/add-visitor/add-visitor.component.html, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts, src/app/super-admin/edit-faculty/edit-faculty.component.html, src/app/super-admin/edit-student/edit-student.component.html, src/app/super-admin/edit-visitor/edit-visitor.component.html, src/app/super-admin/faculty/faculty.component.ts, src/app/super-admin/student/student.component.html, src/app/super-admin/student/student.component.ts, src/app/super-admin/visitor/visitor.component.ts, src/services/records.service.ts
`delete_student.php`
- Receive user_id from `records.service.ts` as the identifier for which student record to delete
- Backend logic for deleting a student from the students table int he database
___
`records.service.ts`
- Added deleteStudent method for connecting to `delete_student.php`
- Pass the user_id recieved from front-end
___
`student.component.ts`
- Front-end logic for removing selected student form the displayed table
- Responsible for passing the user_id of the selected user to be deleted
___
`student.component.html`
- Display modal for delete confirmation
- Display snackbar to inform user of successful deletion 
___
`material-type component`
- fixed back button to work for admin and librarian
`student, faculty, visitor tables`
- Changed the maximum number of items per page to …
=> Manzanas branch

src/app/super-admin/edit-faculty/edit-faculty.component.html, src/app/super-admin/edit-faculty/edit-faculty.component.ts, src/app/super-admin/edit-student/edit-student.component.html, src/app/super-admin/edit-visitor/edit-visitor.component.html, src/app/super-admin/edit-visitor/edit-visitor.component.ts
`edit-faculty.component.html and edit-visitor.component.html`
- fix modal layout and display
=> fix modal display for faculty and visitor edit component

src/app/super-admin/add-faculty/add-faculty.component.html, src/app/super-admin/add-student/add-student.component.html, src/app/super-admin/add-student/add-student.component.ts, src/app/super-admin/edit-student/edit-student.component.html, src/app/super-admin/edit-visitor/edit-visitor.component.html, src/app/super-admin/edit-visitor/edit-visitor.component.ts
Added functioning close buttons for edit-student, edit-visitor, add-student
- buttons route the  page to the previous page
=> Add close buttons for student and visitor edit component

controller_lis/delete_visitor.php, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/super-admin/delete-visitor-success/delete-visitor-success.component.html, src/app/super-admin/delete-visitor-success/delete-visitor-success.component.spec.ts, src/app/super-admin/delete-visitor-success/delete-visitor-success.component.ts, src/app/super-admin/visitor/visitor.component.html, src/app/super-admin/visitor/visitor.component.ts, src/services/records.service.ts
1. **Visitor Component:**
- Implemented methods to open and close a confirmation modal.
- Integrated the delete functionality to call the backend API and handle responses.
2. **Modal Confirmation:**
- Added a modal for confirmation of the delete action.
- If confirmed, the delete action is executed, and the user is redirected to a success page.
3. **Records Service:**
- Added `deleteVisitor` method to call the backend API for deleting a visitor record.
4. **Backend API:**
- Created `delete_visitor.php` script to handle the deletion of visitor records from both the `visitor` and `users` tables in the database.
5. **Routing:**
- Added routing for `DeleteVisitorSuccessComponent` to navigate users to a success page after successful deletion.
6. **Success Component:**
- Created …
=> implement delete functionality for visitors with confirmation modal

controller_lis/db_connection.php, src/app/app.module.ts, src/app/super-admin/books/books.component.ts, src/app/super-admin/faculty/faculty.component.html, src/app/super-admin/faculty/faculty.component.ts, src/app/super-admin/snackbar-delete/snackbar-delete.component.html, src/app/super-admin/snackbar-delete/snackbar-delete.component.spec.ts, src/app/super-admin/snackbar-delete/snackbar-delete.component.ts, src/app/super-admin/student/student.component.html, src/app/super-admin/student/student.component.ts, src/app/super-admin/visitor/visitor.component.html, src/app/super-admin/visitor/visitor.component.ts, src/services/snackbar.service.spec.ts, src/services/snackbar.service.ts
Create snackbar service and delete snackbar component to handle all snackbar display for student, faculty and visitor
=> implement snackbar for faculty and visitor componenet under super admin

src/app/admin/reports/reports.component.css, src/app/admin/reports/reports.component.html, src/app/admin/reports/reports.component.ts, src/app/app.module.ts, src/services/reports.service.spec.ts, src/services/reports.service.ts
Note: run 'npm i' after git pull to install new dependencies from jspdf auto table       
___
`reports.component.css`
- added style for loader indicator
___
`reports.component.html`
- added loader to indicate loading for PDF generation
- increased reports container height
- added generate button functionality
___
- when generate button is clicked get details from materials table then generate PDF based on those details
- connect to `reports.service.ts`
___
`reports.service.ts`
- connect to `fetch_materials.php` to get material table details
___
`fetch_materials.php`
- connect to the database and get details from material table
-     'Accession No.', 'Author', 'Title', 'Copyright', 'Call No.', 'ISBN', 'Remarks'
=> implement PDF preview for inventory under reports component

controller_lis/fetch_categories.php, src/app/admin/reports/reports.component.html, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts, src/services/materials.service.ts
`fetch_categories.php`
- backend logic for getting categories form category table in the database
___
`reports.component.html`
- replaced category dropdown display to be dynamic with correlation to category table in the database
___
- replaced front-end logic for filtering by categories using the fetched data from the category table
___
`materials.service.ts`
- added getCategories method to connect to `fetch_categories.php`
=> implement dynamic categories for books component under super admin

controller_lis/fetch_borrowable_materials.php, src/app/admin/borrow/borrow.component.html, src/app/admin/borrow/borrow.component.ts, src/app/app.module.ts, src/services/borrow.service.spec.ts, src/services/borrow.service.ts
- Added a new PHP file `fetch_borrowable_materials.php` to handle fetching only borrowable books.
- Created a new Angular service `BorrowService` to interact with the new PHP endpoint.
- Updated the `BorrowComponent` to use the `BorrowService` instead of the general `MaterialsService`.
- Modified the category dropdown in `borrow.component.ts` to dynamically exclude categories that do not contain borrowable books.
=> display only borrowable books in borrow table

controller_lis/db_connection.php, src/app/admin/reports/reports.component.html, src/app/admin/reports/reports.component.ts, src/services/reports.service.ts
`reports.component.html`
- Refactor dropdown for category filter to be fetched from category table in the database for maintainability
- Implemented capability to filter by category for the data to be inserted in the generated PDF report based on the selected category on the category dropdown
- Get the value from the selected dropdown then convert it to accession no. format, For example if Circulation, it will be converted to PUPT Circ and that will be passed to the backend to apply category filter.
`reports.service.ts`
- Refactor getMaterials method to take additional parameter for the logic for filtering by category, 
- if 'all' or if nothing is selected, every row from the materials table will be fetched,
- if a matching accession no is passed as parameter, fetch …
=> Implement filtering by category for generating inventory reports

controller_lis/borrow_book.php, controller_lis/fetch_borrowable_materials.php, controller_lis/fetch_material_details.php, src/app/admin/borrow-info/borrow-info.component.html, src/app/admin/borrow-info/borrow-info.component.ts, src/app/admin/borrow-success/borrow-success.component.html, src/app/admin/borrow/borrow.component.ts, src/app/admin/snackbar/snackbar.component.html, src/app/admin/snackbar/snackbar.component.spec.ts, src/app/admin/snackbar/snackbar.component.ts, src/app/app.module.ts, src/services/borrow.service.ts
1. **PHP Backend:**
- **borrow_book.php**: 
- Added to handle the borrowing process, storing the user's borrowing information in the database.
- Automatically calculates the due date based on the category's borrowing duration and updates the `borrowing` table accordingly.
- **fetch_borrowable_materials.php**:
- Integrated overdue checking. Before fetching the list of borrowable materials, the script checks if any borrowed books are overdue and updates their status in the database.
- **fetch_material_details.php**:
- Enhanced to return the borrower's ID (either `student_number` or `emp_number`) when a book is already borrowed. This ID is used to populate the borrow-info field in the frontend.
2. **Angular Frontend:**
- **borrow.component.ts** and **borrow.component.html**:
- Modified to …
=> implement borrowing functionality

src/app/admin/reports/reports.component.ts
- update pdf to contain the following:
-  display current year in the header
- display selected filter on the last page
- display number of total items generated on the last page
- display date and year on the last page
=> update generate report for inventory to display, date, year and total items

src/app/admin/materials-edit/materials-edit.component.css, src/app/admin/materials-edit/materials-edit.component.html, src/app/admin/reports/reports.component.html, src/app/admin/sidebar-admin/sidebar-admin.component.html, src/app/client/material-info/material-info.component.css, src/app/client/material-info/material-info.component.html, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts, src/app/super-admin/super-sidebar/super-sidebar.component.html
- add labels in material-info
- profile and logout button tooltip
-fix height of reports page
- change items on table from 12 to 11 to fix layout
=> Material labels, logout and profile tooltip, fix layout

src/app/client/administrator/administrator.component.html, src/app/client/administrator/administrator.component.ts
make show and hide password work in administrator page
=> make show and hide password work

controller_lis/db_connection.php, controller_lis/get_time_logs.php, src/app/admin/reports/reports.component.html, src/app/admin/reports/reports.component.ts, src/app/app.module.ts, src/services/excel-report-inventory.service.spec.ts, src/services/excel-report-inventory.service.ts, src/services/pdf-report-faculty.service.spec.ts, src/services/pdf-report-faculty.service.ts, src/services/pdf-report-inventory.service.spec.ts, src/services/pdf-report-inventory.service.ts
`app.module.ts`
- Added _PdfReportInventoryService_, _PdfReportFacultyService_, and _ExcelReportInventoryService_ as providers
- Reactor to use services for the logic for generating PDF and Excel for code readability and maintainability
- Moved existing logic to its corresponding services (separated by type of report, _ex. Inventory, Faculty_)
- Methods for using services containing PDF and Excel generation logic:
```
generatePdfInventoryReport() {
this.pdfReportInventoryService.generatePDF(
this.categoryPlaceholder === 'Category' ? '' : this.category,
'pdf-preview',
(loading) => this.isLoading = loading,
(show) => this.showInitialDisplay = show
);
}
generatePdfFacultyReport() {
this.pdfReportFacultyService.generatePDF(
'pdf-preview',
(loading) => this.isLoading = …
```
=> Implement logic to select type of pdf or excel to generate

controller_lis/get_time_logs.php, src/app/admin/reports/reports.component.html, src/app/admin/reports/reports.component.ts, src/app/app.module.ts, src/services/pdf-report-faculty.service.ts, src/services/pdf-report-students.service.spec.ts, src/services/pdf-report-students.service.ts, src/services/records.service.ts
- added generatePdfStudentsReport method to handle student PDF report generation.
- Under report type drop-down replaced _Time-logs_ with `Students `.
`pdf-report-students.service.ts`
- Logic for getting student time log data from backend and them formatting it into proper table format then converting it to a PDF format.
- Uses the same process for PDF generation with the Inventory and Faculty. 
- Connect to `records.service.ts` to be able to connect to backend API  `get_time_logs.php` to obtain time_log data for students
- Convert to PDF format
- Shows pdf preview and then option to download
___
`get_time_logs.php`
- Updated to be able to filter by date range. Its previous functionality remains the same, it is still able to fetch complete …
=> Update PDF report generation, implement filter by date and Implement student log PDF generation

src/app/app.module.ts, src/services/current-date-year.service.spec.ts, src/services/current-date-year.service.ts, src/services/pdf-report-faculty.service.ts, src/services/pdf-report-inventory.service.ts, src/services/pdf-report-students.service.ts
`current-date-year.service.ts`
- contains method to get current date and convert it to Month Day, Year" format
`pdf-report-faculty.service.ts`
`pdf-report-student.service.ts`
`pdf-report-inventory.service.ts`
- refactored to use a service for getting current date to avoid reusing of same logic in multiple files
=> refactor get current date method to use services

src/services/current-date-year.service.ts, src/services/pdf-report-faculty.service.ts, src/services/pdf-report-students.service.ts
`current-date-year.service.ts`
- Add formatDateString method to receive date as parameter then convert its value to month, date, year, format: 
- 2024-08-15 ➡️ Aug 15, 2024
`pdf-report-faculty.service.ts`
`pdf-report-student.service.ts`
- If there are dates selected for the date input fields Display date range selected on the last page of the PDF
- If none are selected do not display the filter on the last page of the PDF
=> implement display of date range selected on report for faculty and student time log

controller_lis/fetch_borrowing_data.php, src/app/admin/reports/reports.component.ts, src/app/app.module.ts, src/services/pdf-report-borrowers.service.spec.ts, src/services/pdf-report-borrowers.service.ts, src/services/return.service.ts
- Added generatePdfBorrowers Report method to handle borrower PDF report generation.
- Allow filter by date range
`pdf-report-borrowers.service.ts`
- Logic for getting borrowers time log data from backend and them formatting it into proper table format, then converting it to a PDF format.
- The same process for PDF generation with the Inventory, Student and Faculty. 
- Connect to `records.service.ts` to be able to connect to backend API  `get_time_logs.php` to obtain time_log data for borrowers 
- Convert to PDF format
- Shows pdf preview and then option to download
___
>  All filters working except for program under inventory reports
PDF:
Excel:
=> implement pdf generation for borrowers report

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/client/register/register.component.html, src/app/super-admin/add-course/add-course.component.html, src/app/super-admin/add-course/add-course.component.spec.ts, src/app/super-admin/add-course/add-course.component.ts, src/app/super-admin/add-department-success/add-department-success.component.html, src/app/super-admin/add-department-success/add-department-success.component.spec.ts, src/app/super-admin/add-department-success/add-department-success.component.ts, src/app/super-admin/add-department/add-department.component.html, src/app/super-admin/add-department/add-department.component.spec.ts, src/app/super-admin/add-department/add-department.component.ts, src/app/super-admin/add-successful/add-successful.component.html, src/app/super-admin/add-successful/add-successful.component.spec.ts, src/app/super-admin/add-successful/add-successful.component.ts, src/app/super-admin/courses/courses.component.html, src/app/super-admin/courses/courses.component.spec.ts, src/app/super-admin/courses/courses.component.ts, src/app/super-admin/departments/departments.component.html, src/app/super-admin/departments/departments.component.spec.ts, src/app/super-admin/departments/departments.component.ts, src/app/super-admin/edit-course/edit-course.component.html, src/app/super-admin/edit-course/edit-course.component.spec.ts, src/app/super-admin/edit-course/edit-course.component.ts, src/app/super-admin/edit-department/edit-department.component.html, src/app/super-admin/edit-department/edit-department.component.spec.ts, src/app/super-admin/edit-department/edit-department.component.ts, src/app/super-admin/faculty/faculty.component.html, src/app/super-admin/student/student.component.html
- Created new components for add, edit and delete for courses and department for super admin
- Add new button for courses on students page on superadmin
- Add new button for departments on faculty page on superadmin
=> Add,edit,delete (maintenance module) for courses and department

src/app/admin/reports/reports.component.ts, src/app/app.module.ts, src/services/excel-report-borrowers.service.spec.ts, src/services/excel-report-borrowers.service.ts, src/services/excel-report-faculty.service.spec.ts, src/services/excel-report-faculty.service.ts, src/services/excel-report-inventory.service.ts, src/services/excel-report-students.service.spec.ts, src/services/excel-report-students.service.ts, src/services/excel-report-visitors.service.spec.ts, src/services/excel-report-visitors.service.ts, src/services/pdf-report-inventory.service.ts, src/services/pdf-report-students.service.ts
- Import ExcelReportFacultyService
- Add **generateExcelFacultyReport** method to handle faculty Excel generation, uses `excel-report-faculty.service.ts`
- Add **generateExcelFacultyReport** method to the **selectExcelReport** method
`app.module.ts`
- Import ExcelReportFacultyService
`excel-report-faculty.service.ts`
- Service for retrieving faculty time log data from the database and then formatting it in an excel file.
- Uses  `records.service.ts` to connect to backend API `get_time_logs.php`
- After formatting the data into a table, display the title at the top most row then the file summary after the table
- Lastly uses _file-saver_ library to handle saving the file into the device as xlsx file
___
- Import ExcelReportBorrowers Service
- …
=> Implement Excel report generation for faculty time logs

controller_lis/add_material.php, src/services/pdf-report-borrowers.service.ts, src/services/pdf-report-faculty.service.ts, src/services/pdf-report-inventory.service.ts, src/services/pdf-report-students.service.ts, src/services/pdf-report-visitors.service.ts
- Display pup logo at the top left side of the pdf file
> Sample preview:
___
`add_material.ph`
- Modified category mapping to use the existing items from the category table in the database instead of hard coded values
=> Add pup logo to pdf reports

controller_lis/add_material_type.php, src/app/admin/add-type/add-type.component.html, src/app/admin/add-type/add-type.component.ts, src/app/admin/materials-type/materials-type.component.html, src/app/admin/materials-type/materials-type.component.ts, src/services/add-material.service.ts
`add-type.component.html`
- Added Borrow duration input field
`add-type.component.ts`
- Method addMaterialType() 
- receive values from the input fields then pass it to: `add-material.service.ts`
`add-material.service.ts`
- Pass the received values to the backend API: `add_material_type.php`
`add_material_type.php`
- Backend API for adding new material type / category to the category table
___
`materials-type.component.html`
- Modify from hardcoded values displayed on the table, to fetched data from he category table
`materials-type.component.ts`
- Pass the fetched data from the backend API: `fetch_categories.php`, to `materials-type.component.html`
- For Total library materials count, values is calculated by getting the total of the values inside the counter column under category table
=> Implement Add Material Type with Dynamic Data Display

controller_lis/delete_student.php
`delete_student.php`
- Updated to also delete the existing student under user table, get the value of user_id column of the student to be deleted in the students table, then look for the same value under id column in the users table the delete both.
=> fix delete student, also delete student from the users table

controller_lis/fetch_librarian.php, controller_lis/update_librarian.php, src/app/admin/profile/profile.component.html, src/app/admin/profile/profile.component.ts, src/app/app.module.ts, src/services/librarian.service.spec.ts, src/services/librarian.service.ts
1. Added fetch_librarian.php to retrieve librarian details.
1. Added update_librarian.php to update librarian information.
1. Created LibrarianService with methods getLibrarianById and updateLibrarian for interacting with the API.
1. Modified profile.component.html and profile.component.ts to handle fetching, displaying, and updating profile details.
1. Updated app.module.ts to import and provide LibrarianService.
The password update feature is still under development. The current implementation displays the password field as **** and is readonly.
=> Implement profile management for librarian: Fetch and update details

src/app/client/register/register.component.html, src/styles.css
- change the term "division" to "department" in faculty registration
- remove arrows to increment and decrement in number type fields
=> minimal fix in registration

controller_lis/generate_penalty.php, src/app/admin/materials-edit/materials-edit.component.html, src/app/admin/return/return.component.ts, src/services/pdf-penalty-receipt.service.ts
1. **Dynamic Librarian Name:**
- The name of the librarian is now dynamically fetched from the `librarian` table in the database. This allows the PDF to automatically reflect the current librarian without requiring code updates.
- The PHP script (`generate.penalty.php`) was modified to query the `librarian` table and include the librarian's name in the JSON response.
- The Angular service (`pdf-penalty-receipt.service.ts`) was updated to utilize this dynamic librarian name when generating the PDF.
2. **Improved PDF Formatting:**
- **Borders:** Added a border around each section of the PDF for both the student's and library's copies, improving the visual structure of the document.
- **Cutting Line:** Introduced a cutting line (dashed line) in the middle of the PDF to facilitate easy …
=> Generate Dynamic Librarian Name and Improve PDF Formatting

controller_lis/update_librarian.php, package-lock.json, package.json, src/app/admin/profile/profile.component.html, src/app/admin/profile/profile.component.ts
- Run **`npm install`** after pulling these changes to install the SHA256 hashing library that was added
##
1. Password is only updated if explicitly changed:
- The password will now only be updated if the user completes the password confirmation process (entering current, new, and re-entering the new password) and clicks "Save Changes."
2. Canceling the password update resets the process:
- If the user cancels while editing the password, all password-related fields (current, new, and re-enter) are reset, and the original password remains unchanged.
3. Prevents rehashing the password:
- The original hashed password will not be rehashed or overwritten when saving changes if no new password is provided, preventing issues with password validation on future updates.
4. Improved user feedback …
=> Enhance Password Update Flow with Modals, Validation Notes, and SHA256 Hashing

controller_lis/fetch_materials.php, package-lock.json, src/app/admin/materials/materials.component.html, src/app/admin/materials/materials.component.ts, src/app/super-admin/books/books.component.css, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts, src/services/materials.service.ts
`node_modules/body-parser`
- updated to version 1.20.3
`node_modules/express`
- updated to version 4.20.0
`node_modules/merge-descriptors`
- updated to version 1.0.3
`node_modules/path-to-regexp`
- updated to version 0.1.10
`node_modules/send`
- updated to version 0.19.0
`node_modules/serve-static`
- updated to version 0.19.0
___
`books.component.ts`
`materials.componenet.ts`
- Updated accession number sorting, sort by category first in alphabetical, toggleable between ascending and descending order 
- Then sort the category by id since the id of the latest added has the bigger number resulting in correct ascending or descending order
`books.component.html`
`materials.componenet.html`
- Updated with working arrow labels to signify ascending or descending order
`fetch_materials.php`
- …
=> fix high vulnerabilites by running npm audit fix

controller_lis/add_material.php, controller_lis/fetch_materials.php, controller_lis/update_material.php, src/app/admin/materials-add/materials-add.component.html, src/app/admin/materials-add/materials-add.component.ts, src/services/add-material.service.ts, src/services/materials.service.ts
- fixed variable mismatch between front end and backend for cateogryid
- updated front-end for add material component to fetch categories dynamically from the database
=> fix add and edit material categoryid not being passed to backend

controller_lis/fetch_borrowing_data.php, controller_lis/fetch_materials.php, src/app/admin/reports/reports.component.html, src/app/admin/reports/reports.component.ts, src/app/admin/return/return.component.html, src/app/admin/return/return.component.ts, src/services/excel-report-inventory.service.ts, src/services/materials.service.ts, src/services/pdf-report-inventory.service.ts, src/services/reports.service.ts, src/services/return.service.ts
`controller_lis/fetch_materials.php`
- Updated to handle filtering by program, matches the values passed with the title or subject column
- Works with category filter
`src/app/admin/reports/reports.component.ts`
- Updated to handle dynamic display for program
`src/services/excel-report-inventory.service.ts`
`src/services/pdf-report-inventory.service.ts`
- Updated to be able to handle program filters in report generation both for excel and pdf
`materials.service.ts`
`reports.service.ts`
- Added parameter to hold the program value to pass to the payload to be sent to the backend API
___
`fetch_borrowing_data.php`
- updated to handle logic for filtering based on user searching, compare key words using WHERE LIKE %''%
`return component`
- updated search input to track user input
- searching …
=> implement program filters for generating reports

controller_lis/check_registration.php, controller_lis/fetch_borrowing_data.php, src/app/admin/return/return.component.html, src/app/admin/return/return.component.ts, src/app/client/register/register.component.html, src/app/client/register/register.component.ts, src/services/register.service.ts
**Pagination:**
- Modified the fetchBorrowingData method to handle pagination.
- Added methods nextPage and previousPage for navigating between pages.
- Updated the template in return.component.html to display the current page and total pages, with disabled states for pagination buttons when appropriate.
- Adjusted the table to display the paginated list of items instead of the entire dataset.
**Sorting:**
- Non-returned books are now sorted by claim_date in descending order (most recent at the top).
- Returned books are sorted by return_date in descending order (most recent returns at the top).
- Updated the fetchBorrowingData() method in return.component.ts to accommodate the new sorting logic, ensuring users see the most recent transactions first.
**Validation Enhancements:**
- Error …
=> Added validation in registration form and Added pagination and Sort the return table

src/app/client/administrator/administrator.component.html, src/app/client/search-book/search-book.component.html, src/app/client/time-in/time-in.component.html, src/app/client/time-out/time-out.component.html, src/app/client/timein-already/timein-already.component.html, src/app/client/timein-success/timein-success.component.html, src/app/client/timeout-success/timeout-success.component.html
fix mobile responsiveness of timein, timeout and timein already component
=> timein, timeout and timein already component responsiveness

src/app/admin/analytics/analytics.component.html, src/app/admin/analytics/monthly-category-donut/monthly-category-donut.component.html, src/app/admin/analytics/monthly-users/monthly-users.component.html, src/app/admin/analytics/top-ten-user-timein/top-ten-user-timein.component.html, src/app/admin/materials-type/materials-type.component.html, src/app/client/search-book/search-book.component.html
- Fix analytics page mobile responsive
- add cards for total number of students, faculty, visitors, category, materials, courses, department, borrower in analytics page
- request a book frontend
=> Request a book front end and analytics page

controller_lis/delete_material.php, controller_lis/fetch_accession_no.php, src/app/admin/materials-add/materials-add.component.ts, src/services/add-material.service.ts, src/services/environments/local-environment.ts
add Url for online database in Hostinger
=> update apiUrl connection

controller_lis/check_registration.php, src/app/admin/profile/profile.component.html, src/app/client/register/register.component.html, src/app/client/register/register.component.ts, src/services/register.service.ts
- Replaced the old profile picture with a new image (`assets/pup.png`).
- Adjusted the layout to ensure the profile picture remains circular.
- Added appropriate spacing between the profile picture and the details (name, email, etc.).
- Fixed the alignment to move the text fields further away from the profile image for better readability.
1. **Simultaneous Validation and Registration Check**:
- The system now checks both the identifier (student number, faculty code, or visitor identifier) and the contact number for both format errors and whether they are already registered at the same time.
- This fixes the issue where only one error message was shown when both fields had issues.
2. **Concurrent Checks for Identifier and Contact**:
- Instead of checking the identifier and contact one …
=> Enhance User Profile and Registration Flow with Updated Layout and Simultaneous Validation

src/app/admin/materials-add/materials-add.component.html, src/app/super-admin/edit-faculty-success/edit-faculty-success.component.html, src/app/super-admin/edit-faculty/edit-faculty.component.html, src/app/super-admin/edit-student/edit-student.component.html, src/app/super-admin/edit-success/edit-success.component.html, src/app/super-admin/edit-visitor/edit-visitor.component.html
- remove accession number input field in add material
- remove status input field in add material
- fix mobile responsive of edit type of users
- fix mobile responsive of success message in edit type of users
=> Edit type and success message mobile responsive, removal of Accession number and status input field in add material

controller_lis/get_time_logs.php, src/app/admin/materials-add/materials-add.component.ts, src/app/admin/records/records.component.html, src/app/admin/records/records.component.ts, src/app/super-admin/user-record/user-record.component.html, src/app/super-admin/user-record/user-record.component.ts, src/services/pdf-report-students.service.ts, src/services/records.service.ts
Input from the search bar will be used to filter the responses and will work for all column of the audit trail table
- works for Name and Student number
- uses debounce time to prevent sending to many requests at once
- search also works with what record type or log type is being requested based on the selected value from the dropdown
=> Implement search feature for audit trail

src/app/super-admin/faculty/faculty.component.html, src/app/super-admin/faculty/faculty.component.ts, src/app/super-admin/student/student.component.html, src/app/super-admin/student/student.component.ts, src/app/super-admin/visitor/visitor.component.html, src/app/super-admin/visitor/visitor.component.ts
clear buttons: 
- Remove the inputted values on the search bar
- Fetch the complete and unfiltered table for student, faculty and visitor
=> add clear button for clearing the search bar

controller_lis/book_request.php, controller_lis/fetch_book_request.php, src/app/admin/analytics/analytics.component.html, src/app/admin/analytics/analytics.component.ts, src/app/app.module.ts, src/app/client/client-snackbar/client-snackbar.component.html, src/app/client/client-snackbar/client-snackbar.component.spec.ts, src/app/client/client-snackbar/client-snackbar.component.ts, src/app/client/search-book/search-book.component.html, src/app/client/search-book/search-book.component.ts, src/services/book-request.service.spec.ts, src/services/book-request.service.ts
1. Added backend (book_request.php) to process book requests and check registration status.
2. Integrated a dropdown in the existing request form for selecting requester_type (student, faculty, or visitor).
3. Implemented form validation to ensure all fields are filled before submission.
4. Created BookRequestService to handle communication with the backend.
5. Implemented ClientSnackbarComponent for displaying success and error messages.
6. Added a modal to notify users if they are not registered.
1. Created fetch_book_request.php to fetch book request data along with the requestor's name based on requester_type.
2. Updated book-request.service.ts to include a method for fetching book requests from the backend.
3. Modified analytics.component.ts to load and display the book request data …
=> Implement Book Request Functionality with Dynamic Data Fetching and Pagination

src/app/admin/analytics/analytics.component.html, src/app/super-admin/faculty/faculty.component.html, src/app/super-admin/student/student.component.html, src/services/excel-report-faculty.service.ts, src/services/excel-report-students.service.ts, src/services/excel-report-visitors.service.ts, src/services/pdf-report-faculty.service.ts, src/services/pdf-report-students.service.ts, src/services/pdf-report-visitors.service.ts, src/services/records.service.ts
- Fixed bug were generating reports used page limit as the number of rows to fetch in total instead of the number of rows to fetch per page.
- Fixed bug where names for student and faculty are not being displayed on the delete modal
=> fix user report generation, not all pages being loaded

src/app/admin/analytics/analytics.component.html, src/app/admin/borrow-info/borrow-info.component.html, src/app/admin/borrow/borrow.component.html, src/app/admin/materials/materials.component.html, src/app/admin/navbar-admin/navbar-admin.component.html, src/app/admin/records/records.component.html, src/app/admin/return/return.component.html, src/app/client/material-info/material-info.component.html
- make searchbar 1/2 width so it is not too long
- revise analytics graphs placements
- remove unnecessary bottom paddings on other admin components
=> revise searchbar width and analytics graphs placements (admin side)

controller_lis/fetch_analytics_card_details.php, src/app/admin/analytics/analytics.component.html, src/app/admin/analytics/analytics.component.ts, src/app/app.module.ts, src/services/analytics.service.spec.ts, src/services/analytics.service.ts
`controller_lis/fetch_analytics_card_details.php`
- backend logic for fetching analytics card details:
>  sample response
```
{
"total_users": "54",
"user_type_counts": {
"faculty": "10",
"student": "41",
"visitor": "3"
},
"total_materials": "7281",
"category_counts": {
"Business Plan": "25",
"Case Study": "1",
"Circulation": "3096",
"Donation": "353",
"E-Book": "65",
"Feasibility": "413",
"Fiction": "65",
"Filipiñana": "1748",
"History": "0",
"OJT/Internship": "0",
"PDF": "0",
"Reference": "267",
"Thesis and Disertation": "1195",
"Training Manual": "53"
},
"total_categories": "14",
"total_departments": "9",
"total_programs": "9",
"total_charged": "1",
"total_overdue": "15",
"total_time_ins": "2",
"total_time_outs": "1"
}
```
`src/services/analytics.service.ts`
- service for connecting to …
=> implement dynamic fetching of details for analytics page cards

src/app/admin/add-success/add-success.component.html, src/app/admin/profile/profile.component.html, src/app/admin/return/return.component.html, src/app/client/search-book/search-book.component.html, src/app/super-admin/add-course/add-course.component.html, src/app/super-admin/add-department-success/add-department-success.component.html, src/app/super-admin/add-department/add-department.component.html, src/app/super-admin/add-faculty-success/add-faculty-success.component.html, src/app/super-admin/add-faculty/add-faculty.component.html, src/app/super-admin/add-student/add-student.component.html, src/app/super-admin/add-visitor-success/add-visitor-success.component.html, src/app/super-admin/add-visitor/add-visitor.component.html, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts, src/app/super-admin/courses/courses.component.html, src/app/super-admin/departments/departments.component.html, src/app/super-admin/edit-course/edit-course.component.html, src/app/super-admin/edit-department/edit-department.component.html, src/app/super-admin/edit-faculty-success/edit-faculty-success.component.html, src/app/super-admin/edit-faculty/edit-faculty.component.html, src/app/super-admin/edit-student/edit-student.component.html, src/app/super-admin/edit-success/edit-success.component.html, src/app/super-admin/edit-visitor/edit-visitor.component.html, src/app/super-admin/faculty/faculty.component.html, src/app/super-admin/navbar-super-admin/navbar-super-admin.component.css, src/app/super-admin/navbar-super-admin/navbar-super-admin.component.html, src/app/super-admin/student/student.component.html, src/app/super-admin/user-record/user-record.component.html, src/app/super-admin/user-record/user-record.component.ts, src/app/super-admin/visitor/visitor.component.html
- revise superadmin navbar change icons to words
- fix spacings, corner radius and background color of components in superadmin
=> Revise superadmin navbar and overall redesign of components

src/app/admin/borrow/borrow.component.html, src/app/admin/materials/materials.component.html, src/app/admin/navbar-admin/navbar-admin.component.html, src/app/admin/records/records.component.html, src/app/admin/records/records.component.ts, src/app/admin/return/return.component.html, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts, src/app/super-admin/faculty/faculty.component.html, src/app/super-admin/user-record/user-record.component.html, src/app/super-admin/user-record/user-record.component.ts, src/app/super-admin/visitor/visitor.component.html
- separate user logs and user records in admin
- add email in visitor table in superadmin
- fix spacings of components in pages in admin and superadmin
- modify the items per page in table in records(admin) and audit trail(admin)
- add checkbox and delete button in materials table in superadmin
=> separate logs and records in admin (librarian)

src/app/admin/materials-add/materials-add.component.html, src/app/admin/materials/materials.component.html, src/app/admin/materials/materials.component.ts, src/app/admin/navbar-admin/navbar-admin.component.html, src/app/admin/request/request.component.html, src/app/admin/request/request.component.spec.ts, src/app/admin/request/request.component.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts
- add checkbox for materials table in admin
- add delete and weed out button for superadmin
- add weedout button for admin
- separate book request from analytics (can be navigated by avatar dropdown in navbar)
- created new component for book requests
- resize the add material form
=> checkbox in materials table for admin, weed-out and delete button, separate book request from analytics

controller_lis/fetch_accession_no.php, src/app/super-admin/books/books.component.html
- uncomment delete buttons for material page under super admin
- update counter for accession number
=> update materials pag under admin side, display delete button

controller_lis/auto_timeout.php, cron-job.js, package-lock.json, package.json
- Run npm install after pulling the changes to install the required dependencies.
#
- Added cron-job.js script to schedule the execution of auto_timeout.php daily at 8 PM using node-cron.
- Implemented auto_timeout.php to update the time_out field in the time_log table for entries with NULL values.
=> add cron-job script and auto_timeout.php

src/app/admin/analytics/analytics.component.html, src/app/admin/materials/materials.component.html, src/app/admin/materials/materials.component.ts, src/app/admin/records/records.component.html, src/app/admin/records/records.component.ts, src/app/client/register/register.component.html, src/app/client/register/register.component.ts, src/app/client/time-in/time-in.component.html, src/app/super-admin/books/books.component.html, src/app/super-admin/books/books.component.ts
- add checkbox to faculty records for sending material requests
- add "send book request" for faculty in faculty records
- add confirmation to mark selected materials as "weed out" in librarian account
- add confirmation to mark selected materials as "weed out" in Super admin
- add confirmation to mass delete materials in superadmin
- remove library hours note in time-in form
- make registration link more visible by changing text color to blue
=> Checkbox to faculty records, weed out and mass delete material confirmation and user registration details confirmation modal

controller_lis/fetch_analytics_card_details.php, controller_lis/get_time_logs.php, src/app/client/register/register.component.ts, src/app/client/search-book/search-book.component.html, src/app/client/search-book/search-book.component.ts
- Removed the auto-timeout logic from get_time_logs.php to reduce redundancy.
- Added the auto-timeout logic to fetch_analytics_card_details.php, ensuring it runs whenever the analytics page is accessed.
- The logic updates time_out values for previous days and today's entries (after 8 PM).
- Updated the `validateEmpNumber()` method to use the new pattern `^FA\d{4}TG\d{4}$`, where:
- `FA` is followed by a 4-digit number,
- `TG` is followed by another 4-digit number.
**Automatic Requester Type Detection:**
- Implemented a method to automatically detect the requester type based on the input format (Student Number, Faculty Code, or Identifier) in the search-book.component.ts.
- Removed default requester type to ensure it is dynamically assigned based on the input.
**Requester Validation:**
- …
=> Refactor and Validation Enhancements for Auto-Timeout, Faculty Code, and Book Requests
